apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisdompet-deployment
  labels:
    app: wisdompet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisdompet
  template:
    metadata:
      labels:
        app: wisdompet
    spec:
      containers:
      - name: wisdompet
        image: apoorvabhishek/wisdom-pet:1.0
        # imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-url
---
apiVersion: v1
kind: Service
metadata:
  name: wisdompet-service
spec:
  type: NodePort 
  selector:
    app: wisdompet
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30101